version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
      - gems_backup:/usr/local/lib/ruby/gems/2.5.0
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=myrailsapp.docker
  postgres:
    image: postgres:9.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=password
volumes:
  pg_data: {}
  gems: {}
  gems_backup: {}